---
# title: "class_2019-03-05"
# author: "Beau Meche"
# date: "March 5, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(gapminder)
library(gganimate)
library(tidyverse)
```

```{r make_plot, echo=FALSE, cache = TRUE, warning=FALSE}
x <- gapminder %>% 
  # filter(year == 1952) %>%
  mutate(continent = fct_collapse(continent, Asia = c("Asia", "Oceania"))) %>% 
  filter(continent != "Europe") %>% 
  # filter(country %in% c("South Africa", "Mexico", "China")) %>%
  
  ggplot(aes(x = gdpPercap, y = lifeExp, size = pop, color = country)) +
    geom_point(alpha = 0.6, show.legend = FALSE) +
    scale_x_log10(breaks = c(1000, 10000),
                  labels = c("$1000", "$10000")) +
    scale_color_manual(values = country_colors) +
  facet_grid(~continent) +
  labs(x = "GDP Per Capita",
       y = "Life Expectancy") +
  transition_time(year) +
  labs(title = "The World Gets Better Every Year")
x

# x + transition_states(year, ) +
#   ggtitle('The World Gets Better Every Year: {closest_state}')

  
```
